// customerH5/src/pages/login/login.vue
<template>
  <view class="login-container">
    <view class="login-header">
      <text class="title">欢迎登录</text>
      <text class="subtitle">客户中心</text>
    </view>
    
    <view class="login-form">
      <view class="form-item">
        <text class="label">用户名</text>
        <input 
          class="input" 
          v-model="formData.username" 
          placeholder="请输入用户名"
          placeholder-class="placeholder"
        />
      </view>
      
      <view class="form-item">
        <text class="label">密码</text>
        <input 
          class="input" 
          v-model="formData.password" 
          type="password"
          placeholder="请输入密码"
          placeholder-class="placeholder"
        />
      </view>
      
      <button class="login-btn" @click="handleLogin" :loading="loading">
        {{ loading ? '登录中...' : '登录' }}
      </button>
      
      <view class="register-link">
        <text>还没有账号？</text>
        <text class="link" @click="goToRegister">立即注册</text>
      </view>
    </view>
  </view>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { useUserStore } from '@/store/user.js'

const formData = ref({
  username: '',
  password: ''
})

const loading = ref(false)
const userStore = useUserStore()

onMounted(() => {
  const pages = getCurrentPages()
  const currentPage = pages[pages.length - 1]
  if (currentPage && currentPage.options) {
    if (currentPage.options.username) {
      formData.value.username = decodeURIComponent(currentPage.options.username)
    }
    if (currentPage.options.password) {
      formData.value.password = decodeURIComponent(currentPage.options.password)
    }
  }
})

const handleLogin = async () => {
  if (!formData.value.username || !formData.value.password) {
    uni.showToast({
      title: '请输入用户名和密码',
      icon: 'none'
    })
    return
  }
  
  loading.value = true
  try {
    await userStore.login(formData.value.username, formData.value.password)
    uni.showToast({
      title: '登录成功',
      icon: 'success'
    })
    setTimeout(() => {
      uni.switchTab({
        url: '/pages/index/index'
      })
    }, 1000)
  } catch (error) {
    console.error('登录失败:', error)
    let errorMessage = '登录失败'
    
    if (error.response?.data?.message) {
      errorMessage = error.response.data.message
    } else if (error.data?.message) {
      errorMessage = error.data.message
    }
    
    uni.showToast({
      title: errorMessage,
      icon: 'none',
      duration: 3000
    })
  } finally {
    loading.value = false
  }
}

const goToRegister = () => {
  uni.navigateTo({
    url: '/pages/register/register'
  })
}
</script>

<style scoped>
.login-container {
  min-height: 100vh;
  padding: 60rpx 40rpx;
  background-color: var(--background-color);
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
}

.login-header {
  text-align: center;
  margin-bottom: 80rpx;
}

.title {
  display: block;
  font-size: 48rpx;
  font-weight: bold;
  color: var(--primary-color);
  margin-bottom: 20rpx;
  text-shadow: 2rpx 2rpx 4rpx rgba(0, 0, 0, 0.1);
}

.subtitle {
  display: block;
  font-size: 32rpx;
  color: var(--text-secondary);
}

.login-form {
  width: 100%;
  max-width: 600rpx;
  background-color: var(--card-background);
  border-radius: var(--border-radius-lg);
  padding: 60rpx 40rpx;
  box-shadow: var(--shadow-lg);
  border: 2rpx solid var(--border-color);
}

.form-item {
  margin-bottom: 40rpx;
}

.label {
  display: block;
  font-size: 28rpx;
  color: var(--text-primary);
  margin-bottom: 16rpx;
  font-weight: bold;
}

.input {
  width: 100%;
  height: 88rpx;
  padding: 0 20rpx;
  border: 2rpx solid var(--border-color);
  border-radius: var(--border-radius-md);
  font-size: 28rpx;
  box-sizing: border-box;
  background-color: var(--card-background);
  transition: all 0.3s ease;
}

.input:focus {
  outline: none;
  border-color: var(--primary-color);
  box-shadow: 0 0 0 4rpx rgba(231, 76, 60, 0.1);
}

.placeholder {
  color: var(--text-secondary);
}

.login-btn {
  width: 100%;
  height: 88rpx;
  background-color: var(--primary-color);
  color: var(--text-light);
  border: none;
  border-radius: var(--border-radius-md);
  font-size: 32rpx;
  font-weight: bold;
  margin-top: 20rpx;
  box-shadow: var(--shadow-md);
  transition: all 0.3s ease;
  border: 4rpx solid var(--primary-dark);
}

.login-btn:active {
  background-color: var(--primary-dark);
  transform: scale(0.98);
  box-shadow: var(--shadow-sm);
}

.login-btn:disabled {
  background-color: #666;
  border-color: #888;
  cursor: not-allowed;
}

.register-link {
  text-align: center;
  margin-top: 40rpx;
  font-size: 28rpx;
  color: var(--text-secondary);
}

.link {
  color: var(--primary-color);
  margin-left: 10rpx;
  font-weight: bold;
  text-decoration: underline;
}

/* 响应式设计 */
@media (max-width: 750rpx) {
  .login-container {
    padding: 40rpx 20rpx;
  }
  
  .login-form {
    padding: 40rpx 30rpx;
  }
  
  .title {
    font-size: 40rpx;
  }
  
  .subtitle {
    font-size: 28rpx;
  }
  
  .input {
    height: 80rpx;
    font-size: 26rpx;
  }
  
  .login-btn {
    height: 80rpx;
    font-size: 28rpx;
  }
}

/* 动画效果 */
.login-container {
  animation: fadeIn 0.6s ease-out;
}

.login-form {
  animation: slideInUp 0.8s ease-out;
}

@keyframes fadeIn {
  from { opacity: 0; }
  to { opacity: 1; }
}

@keyframes slideInUp {
  from {
    opacity: 0;
    transform: translateY(50rpx);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}
</style>

// src/pages/login/index.tsx
import { View, Text } from '@tarojs/components'
import { useState } from 'react'
import Taro from '@tarojs/taro'
import { Network } from '@/network'

export default function LoginPage() {
  const [username, setUsername] = useState('')
  const [password, setPassword] = useState('')
  const [loading, setLoading] = useState(false)

  const handleLogin = async () => {
    if (!username || !password) {
      Taro.showToast({ title: '请输入用户名和密码', icon: 'none' })
      return
    }

    setLoading(true)
    try {
      console.log('开始登录请求...')
      const res = await Network.request({
        url: '/api/auth/login',
        method: 'POST',
        data: { username, password }
      })

      console.log('登录响应:', res)

      if (res.data.code === 200) {
        // 保存登录信息
        Taro.setStorageSync('token', res.data.data.token)
        Taro.setStorageSync('userInfo', res.data.data.user)

        const role = res.data.data.user.role

        Taro.showToast({ title: '登录成功', icon: 'success' })

        // 根据角色跳转到不同的首页
        setTimeout(() => {
          if (role === 'customer') {
            // 客户角色：跳转到抽奖页
            Taro.switchTab({ url: '/pages/index/index' })
          } else {
            // 员工角色：跳转到客户管理页
            Taro.switchTab({ url: '/pages/customer/index' })
          }
        }, 1000)
      } else {
        Taro.showToast({ title: res.data.msg || '登录失败', icon: 'none' })
      }
    } catch (error: any) {
      console.error('登录错误:', error)
      Taro.showToast({ title: error.message || '网络错误，请重试', icon: 'none' })
    } finally {
      setLoading(false)
    }
  }

  return (
    <View className="login-page min-h-screen bg-red-600 p-4 flex flex-col items-center justify-center">
      <View className="mb-8">
        <Text className="block text-6xl mb-3">🧧</Text>
        <Text className="block text-2xl font-bold text-white">春节幸运大转盘</Text>
        <Text className="block text-sm text-red-100 mt-2">小店客户管理系统</Text>
      </View>

      <View className="w-full max-w-sm bg-white rounded-2xl p-6 shadow-lg">
        <View className="mb-4">
          <Text className="block text-base font-semibold text-gray-800 mb-2">用户名</Text>
          <View className="bg-gray-50 rounded-xl px-4 py-3">
            <input
              className="w-full bg-transparent text-base outline-none"
              placeholder="请输入用户名"
              value={username}
              onInput={(e) => setUsername(e.currentTarget.value)}
              disabled={loading}
            />
          </View>
        </View>

        <View className="mb-6">
          <Text className="block text-base font-semibold text-gray-800 mb-2">密码</Text>
          <View className="bg-gray-50 rounded-xl px-4 py-3">
            <input
              className="w-full bg-transparent text-base outline-none"
              type="password"
              placeholder="请输入密码"
              value={password}
              onInput={(e) => setPassword(e.currentTarget.value)}
              disabled={loading}
            />
          </View>
        </View>

        <button
          className={`w-full rounded-xl py-3 font-semibold ${
            loading ? 'bg-gray-400 text-gray-200' : 'bg-red-600 text-white active:bg-red-700'
          }`}
          onClick={handleLogin}
          disabled={loading}
        >
          {loading ? '登录中...' : '登录'}
        </button>

        <View className="mt-4 flex justify-between items-center">
          <Text className="text-xs text-gray-400">默认账号: admin / 密码: 123456</Text>
          <Text
            className="text-xs text-red-600 font-semibold"
            onClick={() => Taro.navigateTo({ url: '/pages/register/index' })}
          >
            去注册
          </Text>
        </View>
      </View>

      <View className="mt-6">
        <Text className="text-xs text-red-200">春节快乐 · 万事如意</Text>
      </View>
    </View>
  )
}
