// archives/v2.0/src/pages/register/index.tsx
import { View, Text, Input, Button } from '@tarojs/components'
import { useState } from 'react'
import Taro from '@tarojs/taro'
import { Network } from '@/network'
import { FormValidator, commonRules } from '@/utils/validator'

export default function RegisterPage() {
  const [formData, setFormData] = useState({
    username: '',
    password: '',
    confirmPassword: '',
    name: '',
    phone: ''
  })
  const [loading, setLoading] = useState(false)
  const [errors, setErrors] = useState({
    username: '',
    password: '',
    confirmPassword: '',
    name: '',
    phone: ''
  })

  const validator = new FormValidator({
    username: [
      {
        required: true,
        message: '请输入用户名'
      },
      {
        minLength: 3,
        message: '用户名至少3个字符'
      }
    ],
    password: [
      {
        required: true,
        message: '请输入密码'
      },
      {
        minLength: 6,
        message: '密码至少6个字符'
      }
    ],
    confirmPassword: [
      {
        required: true,
        message: '请确认密码'
      },
      {
        validator: (value: string) => {
          return value === formData.password || '两次密码不一致'
        }
      }
    ],
    name: [
      {
        required: true,
        message: '请输入姓名'
      }
    ],
    phone: [
      {
        pattern: /^1[3-9]\d{9}$/,
        message: '请输入正确的手机号'
      }
    ]
  })

  const validateField = (fieldName: string, value: string) => {
    validator.setFieldValue(fieldName, value)
    const isValid = validator.validateField(fieldName)
    const error = validator.getFieldError(fieldName) || ''
    setErrors(prev => ({ ...prev, [fieldName]: error }))
    return isValid
  }

  const handleInputChange = (field: string, value: string) => {
    setFormData(prev => ({ ...prev, [field]: value }))
    if (value) {
      validateField(field, value)
    } else {
      setErrors(prev => ({ ...prev, [field]: '' }))
    }
  }

  const validateForm = () => {
    let isValid = true
    for (const field in formData) {
      if (field === 'confirmPassword') {
        validator.setFieldValue('confirmPassword', formData.confirmPassword)
      } else {
        validator.setFieldValue(field, formData[field])
      }
      const fieldValid = validator.validateField(field)
      if (!fieldValid) {
        isValid = false
        const error = validator.getFieldError(field) || ''
        setErrors(prev => ({ ...prev, [field]: error }))
      }
    }
    return isValid
  }

  const handleRegister = async () => {
    if (!validateForm()) {
      Taro.showToast({ title: '请检查输入信息', icon: 'none' })
      return
    }

    setLoading(true)
    try {
      console.log('开始注册请求...', formData)

      const res = await Network.request({
        url: '/api/auth/register',
        method: 'POST',
        data: {
          username: formData.username,
          password: formData.password,
          name: formData.name,
          role: 'customer',
          phone: formData.phone
        }
      })

      console.log('注册响应:', res)

      if (res.data.code === 200) {
        Taro.showToast({ title: '注册成功', icon: 'success' })

        setTimeout(() => {
          Taro.setStorageSync('token', res.data.data.token)
          Taro.setStorageSync('userInfo', res.data.data.user)

          Taro.showToast({ title: '登录成功', icon: 'success' })

          setTimeout(() => {
            Taro.reLaunch({ url: '/pages/index/index' })
          }, 1000)
        }, 1000)
      } else {
        Taro.showToast({ title: res.data.msg || '注册失败', icon: 'none' })
      }
    } catch (error: any) {
      console.error('注册错误:', error)
    } finally {
      setLoading(false)
    }
  }

  const handleBackToLogin = () => {
    Taro.navigateBack()
  }

  return (
    <View className="register-page min-h-screen bg-red-600 p-4 flex flex-col items-center justify-center">
      <View className="mb-10">
        <Text className="block text-7xl mb-4">🧧</Text>
        <Text className="block text-3xl font-bold text-white">用户注册</Text>
        <Text className="block text-base text-red-100 mt-3">注册成为客户，参与抽奖赢大奖</Text>
      </View>

      <View className="w-full max-w-sm bg-white rounded-2xl p-8 shadow-lg">
        <View className="mb-5">
          <Text className="block text-lg font-semibold text-gray-800 mb-3">用户名 *</Text>
          <View className={`bg-gray-50 rounded-xl px-5 py-4 ${errors.username ? 'border-2 border-red-500' : ''}`}>
            <Input
              className="w-full bg-transparent text-lg outline-none"
              placeholder="请输入用户名（至少3个字符）"
              value={formData.username}
              onInput={(e) => handleInputChange('username', e.detail.value)}
              disabled={loading}
            />
          </View>
          {errors.username && (
            <Text className="block text-sm text-red-500 mt-2">{errors.username}</Text>
          )}
        </View>

        <View className="mb-5">
          <Text className="block text-lg font-semibold text-gray-800 mb-3">姓名 *</Text>
          <View className={`bg-gray-50 rounded-xl px-5 py-4 ${errors.name ? 'border-2 border-red-500' : ''}`}>
            <Input
              className="w-full bg-transparent text-lg outline-none"
              placeholder="请输入真实姓名"
              value={formData.name}
              onInput={(e) => handleInputChange('name', e.detail.value)}
              disabled={loading}
            />
          </View>
          {errors.name && (
            <Text className="block text-sm text-red-500 mt-2">{errors.name}</Text>
          )}
        </View>

        <View className="mb-5">
          <Text className="block text-lg font-semibold text-gray-800 mb-3">手机号</Text>
          <View className={`bg-gray-50 rounded-xl px-5 py-4 ${errors.phone ? 'border-2 border-red-500' : ''}`}>
            <Input
              className="w-full bg-transparent text-lg outline-none"
              type="number"
              placeholder="请输入手机号（选填）"
              value={formData.phone}
              onInput={(e) => handleInputChange('phone', e.detail.value)}
              disabled={loading}
            />
          </View>
          {errors.phone && (
            <Text className="block text-sm text-red-500 mt-2">{errors.phone}</Text>
          )}
        </View>

        <View className="mb-5">
          <Text className="block text-lg font-semibold text-gray-800 mb-3">密码 *</Text>
          <View className={`bg-gray-50 rounded-xl px-5 py-4 ${errors.password ? 'border-2 border-red-500' : ''}`}>
            <Input
              className="w-full bg-transparent text-lg outline-none"
              password
              placeholder="请输入密码（至少6个字符）"
              value={formData.password}
              onInput={(e) => handleInputChange('password', e.detail.value)}
              disabled={loading}
            />
          </View>
          {errors.password && (
            <Text className="block text-sm text-red-500 mt-2">{errors.password}</Text>
          )}
        </View>

        <View className="mb-6">
          <Text className="block text-lg font-semibold text-gray-800 mb-3">确认密码 *</Text>
          <View className={`bg-gray-50 rounded-xl px-5 py-4 ${errors.confirmPassword ? 'border-2 border-red-500' : ''}`}>
            <Input
              className="w-full bg-transparent text-lg outline-none"
              password
              placeholder="请再次输入密码"
              value={formData.confirmPassword}
              onInput={(e) => handleInputChange('confirmPassword', e.detail.value)}
              disabled={loading}
            />
          </View>
          {errors.confirmPassword && (
            <Text className="block text-sm text-red-500 mt-2">{errors.confirmPassword}</Text>
          )}
        </View>

        <Button
          className={`w-full rounded-xl py-4 text-lg font-semibold ${
            loading ? 'bg-gray-400 text-gray-200' : 'bg-red-600 text-white active:bg-red-700'
          }`}
          onClick={handleRegister}
          disabled={loading}
        >
          {loading ? '注册中...' : '注册'}
        </Button>

        <View className="mt-6 flex justify-between items-center">
          <Text className="text-sm text-gray-400">注册即表示同意用户协议</Text>
          <Text
            className="text-sm text-red-600"
            onClick={handleBackToLogin}
          >
            已有账号？去登录
          </Text>
        </View>
      </View>

      <View className="mt-8">
        <Text className="text-sm text-red-200">春节快乐 · 万事如意</Text>
      </View>
    </View>
  )
}

// customerH5/src/pages/register/register.vue
<template>
  <view class="register-container">
    <view class="register-header">
      <text class="title">注册账号</text>
      <text class="subtitle">加入我们</text>
    </view>
    
    <view class="register-form">
      <view class="form-item">
        <text class="label">用户名</text>
        <input 
          class="input" 
          v-model="formData.customerCode" 
          placeholder="请输入用户名"
          placeholder-class="placeholder"
        />
      </view>
      
      <view class="form-item">
        <text class="label">密码</text>
        <input 
          class="input" 
          v-model="formData.password" 
          type="password"
          placeholder="请输入密码"
          placeholder-class="placeholder"
        />
      </view>
      
      <view class="form-item">
        <text class="label">确认密码</text>
        <input 
          class="input" 
          v-model="formData.confirmPassword" 
          type="password"
          placeholder="请再次输入密码"
          placeholder-class="placeholder"
        />
      </view>
      
      <view class="form-item">
        <text class="label">手机号</text>
        <input 
          class="input" 
          v-model="formData.phone" 
          type="number"
          placeholder="请输入手机号"
          placeholder-class="placeholder"
        />
      </view>
      
      <view class="form-item">
        <text class="label">姓名</text>
        <input 
          class="input" 
          v-model="formData.customerName" 
          placeholder="请输入姓名"
          placeholder-class="placeholder"
        />
      </view>
      
      <view class="form-item">
        <text class="label">邮箱</text>
        <input 
          class="input" 
          v-model="formData.email" 
          type="email"
          placeholder="请输入邮箱"
          placeholder-class="placeholder"
        />
      </view>
      
      <button class="register-btn" @click="handleRegister" :loading="loading">
        {{ loading ? '注册中...' : '注册' }}
      </button>
      
      <view class="login-link">
        <text>已有账号？</text>
        <text class="link" @click="goToLogin">立即登录</text>
      </view>
    </view>
  </view>
</template>

<script setup>
import { ref } from 'vue'
import { useUserStore } from '@/store/user.js'

const formData = ref({
  customerCode: '',
  password: '',
  confirmPassword: '',
  phone: '',
  customerName: '',
  email: ''
})

const loading = ref(false)
const userStore = useUserStore()

const handleRegister = async () => {
  if (!formData.value.customerCode || !formData.value.password) {
    uni.showToast({
      title: '请输入用户名和密码',
      icon: 'none'
    })
    return
  }
  
  if (formData.value.password !== formData.value.confirmPassword) {
    uni.showToast({
      title: '两次密码不一致',
      icon: 'none'
    })
    return
  }
  
  if (!formData.value.phone) {
    uni.showToast({
      title: '请输入手机号',
      icon: 'none'
    })
    return
  }
  
  loading.value = true
  try {
    const registerData = {
      username: formData.value.customerCode,
      password: formData.value.password,
      phone: formData.value.phone,
      name: formData.value.customerName || formData.value.customerCode,
      email: formData.value.email,
      roleId: 2
    }
    
    await userStore.register(registerData)
    uni.showToast({
      title: '注册成功',
      icon: 'success'
    })
    
    setTimeout(() => {
      uni.redirectTo({
        url: `/pages/login/login?username=${encodeURIComponent(formData.value.customerCode)}&password=${encodeURIComponent(formData.value.password)}`
      })
    }, 1000)
  } catch (error) {
    console.error('注册失败:', error)
    let errorMessage = '注册失败'
    
    if (error.response?.data?.message) {
      errorMessage = error.response.data.message
    } else if (error.data?.message) {
      errorMessage = error.data.message
    }
    
    uni.showToast({
      title: errorMessage,
      icon: 'none',
      duration: 3000
    })
  } finally {
    loading.value = false
  }
}

const goToLogin = () => {
  uni.navigateBack()
}
</script>

<style scoped>
.register-container {
  min-height: 100vh;
  padding: 60rpx 40rpx;
  background-color: var(--background-color);
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
}

.register-header {
  text-align: center;
  margin-bottom: 60rpx;
}

.title {
  display: block;
  font-size: 48rpx;
  font-weight: bold;
  color: var(--primary-color);
  margin-bottom: 20rpx;
  text-shadow: 2rpx 2rpx 4rpx rgba(0, 0, 0, 0.1);
}

.subtitle {
  display: block;
  font-size: 32rpx;
  color: var(--text-secondary);
}

.register-form {
  width: 100%;
  max-width: 600rpx;
  background-color: var(--card-background);
  border-radius: var(--border-radius-lg);
  padding: 60rpx 40rpx;
  box-shadow: var(--shadow-lg);
  border: 2rpx solid var(--border-color);
}

.form-item {
  margin-bottom: 30rpx;
}

.label {
  display: block;
  font-size: 28rpx;
  color: var(--text-primary);
  margin-bottom: 16rpx;
  font-weight: bold;
}

.input {
  width: 100%;
  height: 88rpx;
  padding: 0 20rpx;
  border: 2rpx solid var(--border-color);
  border-radius: var(--border-radius-md);
  font-size: 28rpx;
  box-sizing: border-box;
  background-color: var(--card-background);
  transition: all 0.3s ease;
}

.input:focus {
  outline: none;
  border-color: var(--primary-color);
  box-shadow: 0 0 0 4rpx rgba(231, 76, 60, 0.1);
}

.placeholder {
  color: var(--text-secondary);
}

.register-btn {
  width: 100%;
  height: 88rpx;
  background-color: var(--primary-color);
  color: var(--text-light);
  border: none;
  border-radius: var(--border-radius-md);
  font-size: 32rpx;
  font-weight: bold;
  margin-top: 20rpx;
  box-shadow: var(--shadow-md);
  transition: all 0.3s ease;
  border: 4rpx solid var(--primary-dark);
}

.register-btn:active {
  background-color: var(--primary-dark);
  transform: scale(0.98);
  box-shadow: var(--shadow-sm);
}

.register-btn:disabled {
  background-color: #666;
  border-color: #888;
  cursor: not-allowed;
}

.login-link {
  text-align: center;
  margin-top: 40rpx;
  font-size: 28rpx;
  color: var(--text-secondary);
}

.link {
  color: var(--primary-color);
  margin-left: 10rpx;
  font-weight: bold;
  text-decoration: underline;
}

/* 响应式设计 */
@media (max-width: 750rpx) {
  .register-container {
    padding: 40rpx 20rpx;
  }
  
  .register-form {
    padding: 40rpx 30rpx;
  }
  
  .title {
    font-size: 40rpx;
  }
  
  .subtitle {
    font-size: 28rpx;
  }
  
  .input {
    height: 80rpx;
    font-size: 26rpx;
  }
  
  .register-btn {
    height: 80rpx;
    font-size: 28rpx;
  }
}

/* 动画效果 */
.register-container {
  animation: fadeIn 0.6s ease-out;
}

.register-form {
  animation: slideInUp 0.8s ease-out;
}

@keyframes fadeIn {
  from { opacity: 0; }
  to { opacity: 1; }
}

@keyframes slideInUp {
  from {
    opacity: 0;
    transform: translateY(50rpx);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}
</style>
