// mini-app/src/pages/profile/index.vue
<template>
  <view class="profile-page">
    <view class="header">
      <view class="avatar">
        <view class="avatar-icon">👤</view>
      </view>
      <view class="info">
        <view class="name">{{ userInfo.name || '未登录' }}</view>
        <view class="phone">{{ userInfo.phone || '' }}</view>
      </view>
    </view>
    <view class="stats">
      <view class="stat-item">
        <view class="value">{{ userInfo.points || 0 }}</view>
        <view class="label">积分</view>
      </view>
      <view class="stat-item">
        <view class="value">{{ userInfo.couponCount || 0 }}</view>
        <view class="label">优惠券</view>
      </view>
      <view class="stat-item">
        <view class="value">{{ userInfo.orderCount || 0 }}</view>
        <view class="label">订单</view>
      </view>
    </view>
    <view class="menu">
      <view class="menu-item" @click="goToEditProfile">
        <text class="label">编辑资料</text>
        <text class="arrow">></text>
      </view>
      <view class="menu-item" @click="goToPointsHistory">
        <text class="label">积分历史</text>
        <text class="arrow">></text>
      </view>
      <view class="menu-item" @click="goToPurchaseRecord">
        <text class="label">购买记录</text>
        <text class="arrow">></text>
      </view>
      <view class="menu-item" @click="handleLogout">
        <text class="label">退出登录</text>
        <text class="arrow">></text>
      </view>
    </view>
  </view>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { api } from '../../services/api';

const userInfo = ref({
  name: '',
  phone: '',
  points: 0,
  couponCount: 0,
  orderCount: 0
});

const loadUserInfo = async () => {
  try {
    const user = uni.getStorageSync('user');
    if (user) {
      userInfo.value = {
        ...userInfo.value,
        name: user.name,
        phone: user.phone
      };
      
      // 获取积分信息
      const pointsRes = await api.points.getBalance();
      userInfo.value.points = pointsRes.balance || 0;
      
      // 获取优惠券数量
      const couponsRes = await api.coupon.getMyCoupons();
      userInfo.value.couponCount = couponsRes.length || 0;
      
      // 获取订单数量
      const ordersRes = await api.order.getMyOrders();
      userInfo.value.orderCount = ordersRes.length || 0;
    }
  } catch (error) {
    console.error('获取用户信息失败:', error);
  }
};

const goToEditProfile = () => {
  uni.navigateTo({ url: '/pages/edit-profile/index' });
};

const goToPointsHistory = () => {
  uni.navigateTo({ url: '/pages/points-history/index' });
};

const goToPurchaseRecord = () => {
  uni.navigateTo({ url: '/pages/purchase-record/index' });
};

const handleLogout = () => {
  uni.showModal({
    title: '提示',
    content: '确定要退出登录吗？',
    success: async (res) => {
      if (res.confirm) {
        try {
          await api.auth.logout();
        } catch (error) {
          console.error('退出登录失败:', error);
        } finally {
          uni.removeStorageSync('token');
          uni.removeStorageSync('user');
          uni.reLaunch({ url: '/pages/login/index' });
        }
      }
    }
  });
};

onMounted(() => {
  loadUserInfo();
});
</script>

<style lang="scss" scoped>
.profile-page {
  min-height: 100vh;
  background-color: #f5f5f5;
}

.header {
  display: flex;
  align-items: center;
  padding: 60rpx 40rpx;
  background: linear-gradient(135deg, #dc2626 0%, #b91c1c 100%);
}

.avatar {
  width: 120rpx;
  height: 120rpx;
  border-radius: 50%;
  overflow: hidden;
  margin-right: 30rpx;
  background-color: #ffffff;
  display: flex;
  align-items: center;
  justify-content: center;
}

.avatar-icon {
  font-size: 80rpx;
  line-height: 1;
}

.info {
  flex: 1;
}

.name {
  font-size: 36rpx;
  font-weight: bold;
  color: #ffffff;
  margin-bottom: 10rpx;
}

.phone {
  font-size: 28rpx;
  color: #fca5a5;
}

.stats {
  display: flex;
  background-color: #ffffff;
  padding: 40rpx 0;
  margin-bottom: 20rpx;
}

.stat-item {
  flex: 1;
  text-align: center;
}

.value {
  font-size: 40rpx;
  font-weight: bold;
  color: #dc2626;
  margin-bottom: 10rpx;
}

.label {
  font-size: 24rpx;
  color: #999999;
}

.menu {
  background-color: #ffffff;
}

.menu-item {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 30rpx 40rpx;
  border-bottom: 1rpx solid #f5f5f5;
}

.menu-item:last-child {
  border-bottom: none;
}

.label {
  font-size: 30rpx;
  color: #333333;
}

.arrow {
  font-size: 30rpx;
  color: #999999;
}
</style>

// src/pages/profile/index.tsx
import { View, Text, Button } from '@tarojs/components'
import { useState, useEffect } from 'react'
import Taro from '@tarojs/taro'
import CustomTabBar from '@/components/CustomTabBar'

export default function ProfilePage() {
  const [userInfo, setUserInfo] = useState<any>(null)

  useEffect(() => {
    // 获取用户信息
    const user = Taro.getStorageSync('userInfo')
    setUserInfo(user)
  }, [])

  const handleLogout = () => {
    Taro.showModal({
      title: '退出登录',
      content: '确定要退出登录吗？',
      success: (res) => {
        if (res.confirm) {
          // 清除登录信息
          Taro.removeStorageSync('token')
          Taro.removeStorageSync('userInfo')

          Taro.showToast({ title: '已退出登录', icon: 'success' })

          // 跳转到登录页
          setTimeout(() => {
            Taro.reLaunch({ url: '/pages/login/index' })
          }, 1000)
        }
      }
    })
  }

  const navigateTo = (path: string) => {
    Taro.navigateTo({ url: path })
  }

  // 根据角色显示不同的内容
  const isCustomer = userInfo?.role === 'customer'
  const isStaff = userInfo?.role === 'staff' || userInfo?.role === 'admin'

  return (
    <View className="profile-page min-h-screen bg-gray-50 pb-20">
      {/* 用户信息卡片 */}
      <View className="bg-red-600 p-6 pt-12 pb-8">
        <View className="flex items-center">
          <View className="w-16 h-16 bg-white rounded-full flex items-center justify-center mb-4">
            <Text className="text-3xl">👤</Text>
          </View>
          <View className="ml-4">
            <Text className="block text-xl font-bold text-white">{userInfo?.name || '用户'}</Text>
            <Text className="block text-sm text-red-100">
              {isCustomer ? '客户' : isStaff ? '管理员' : '用户'}
            </Text>
          </View>
        </View>
      </View>

      {/* 客户功能 */}
      {isCustomer && (
        <View className="mt-4 mx-4 bg-white rounded-2xl overflow-hidden shadow-sm">
          <View
            className="flex items-center justify-between p-4 border-b border-gray-100"
            onClick={() => navigateTo('/pages/my-coupon/index')}
          >
            <View className="flex items-center">
              <Text className="block text-2xl mr-3">🎫</Text>
              <Text className="block text-base font-semibold text-gray-800">我的卡券</Text>
            </View>
            <Text className="text-gray-400">›</Text>
          </View>

          <View
            className="flex items-center justify-between p-4 border-b border-gray-100"
            onClick={() => navigateTo('/pages/lottery-record/index')}
          >
            <View className="flex items-center">
              <Text className="block text-2xl mr-3">🎁</Text>
              <Text className="block text-base font-semibold text-gray-800">中奖记录</Text>
            </View>
            <Text className="text-gray-400">›</Text>
          </View>

          <View
            className="flex items-center justify-between p-4 border-b border-gray-100"
            onClick={() => navigateTo('/pages/purchase-record/index')}
          >
            <View className="flex items-center">
              <Text className="block text-2xl mr-3">🛒</Text>
              <Text className="block text-base font-semibold text-gray-800">购买记录</Text>
            </View>
            <Text className="text-gray-400">›</Text>
          </View>

          <View
            className="flex items-center justify-between p-4 border-b border-gray-100"
            onClick={() => navigateTo('/pages/points-history/index')}
          >
            <View className="flex items-center">
              <Text className="block text-2xl mr-3">⭐</Text>
              <Text className="block text-base font-semibold text-gray-800">积分明细</Text>
            </View>
            <Text className="text-gray-400">›</Text>
          </View>

          <View
            className="flex items-center justify-between p-4"
            onClick={() => navigateTo('/pages/edit-profile/index')}
          >
            <View className="flex items-center">
              <Text className="block text-2xl mr-3">👤</Text>
              <Text className="block text-base font-semibold text-gray-800">个人资料</Text>
            </View>
            <Text className="text-gray-400">›</Text>
          </View>
        </View>
      )}

      {/* 员工功能 */}
      {isStaff && (
        <View className="mt-4 mx-4 bg-white rounded-2xl overflow-hidden shadow-sm">
          <View
            className="flex items-center justify-between p-4 border-b border-gray-100"
            onClick={() => navigateTo('/pages/product/index')}
          >
            <View className="flex items-center">
              <Text className="text-2xl mr-3">📦</Text>
              <Text className="text-base font-semibold text-gray-800">产品管理</Text>
            </View>
            <Text className="text-gray-400">›</Text>
          </View>

          <View
            className="flex items-center justify-between p-4 border-b border-gray-100"
            onClick={() => navigateTo('/pages/order/index')}
          >
            <View className="flex items-center">
              <Text className="text-2xl mr-3">📝</Text>
              <Text className="text-base font-semibold text-gray-800">订单管理</Text>
            </View>
            <Text className="text-gray-400">›</Text>
          </View>

          <View
            className="flex items-center justify-between p-4 border-b border-gray-100"
            onClick={() => navigateTo('/pages/prize/index')}
          >
            <View className="flex items-center">
              <Text className="text-2xl mr-3">🎁</Text>
              <Text className="text-base font-semibold text-gray-800">奖品管理</Text>
            </View>
            <Text className="text-gray-400">›</Text>
          </View>

          <View
            className="flex items-center justify-between p-4 border-b border-gray-100"
            onClick={() => navigateTo('/pages/coupon/index')}
          >
            <View className="flex items-center">
              <Text className="text-2xl mr-3">🧧</Text>
              <Text className="text-base font-semibold text-gray-800">卡券管理</Text>
            </View>
            <Text className="text-gray-400">›</Text>
          </View>

          <View
            className="flex items-center justify-between p-4"
            onClick={() => navigateTo('/pages/points-rule/index')}
          >
            <View className="flex items-center">
              <Text className="text-2xl mr-3">⚙️</Text>
              <Text className="text-base font-semibold text-gray-800">积分规则管理</Text>
            </View>
            <Text className="text-gray-400">›</Text>
          </View>
        </View>
      )}

      {/* 退出登录 */}
      <View className="mx-4 mt-4">
        <Button
          className="bg-white text-red-600 rounded-2xl"
          onClick={handleLogout}
        >
          退出登录
        </Button>
      </View>

      {/* 自定义TabBar */}
      <CustomTabBar />
    </View>
  )
}
