// archives/v1.0/src/pages/login/index.tsx
import { View, Text } from '@tarojs/components'
import { useState } from 'react'
import Taro from '@tarojs/taro'
import { Network } from '@/network'

export default function LoginPage() {
  const [username, setUsername] = useState('')
  const [password, setPassword] = useState('')
  const [loading, setLoading] = useState(false)

  const handleLogin = async () => {
    if (!username || !password) {
      Taro.showToast({ title: '请输入用户名和密码', icon: 'none' })
      return
    }

    setLoading(true)
    try {
      console.log('开始登录请求...')
      const res = await Network.request({
        url: '/api/auth/login',
        method: 'POST',
        data: { username, password }
      })

      console.log('登录响应:', res)

      if (res.data.code === 200) {
        // 保存登录信息
        Taro.setStorageSync('token', res.data.data.token)
        Taro.setStorageSync('userInfo', res.data.data.user)

        const role = res.data.data.user.role

        Taro.showToast({ title: '登录成功', icon: 'success' })

        // 根据角色跳转到不同的首页
        setTimeout(() => {
          if (role === 'customer') {
            // 客户角色：跳转到抽奖页
            Taro.reLaunch({ url: '/pages/index/index' })
          } else {
            // 员工角色：跳转到客户管理页
            Taro.reLaunch({ url: '/pages/customer/index' })
          }
        }, 1000)
      } else {
        Taro.showToast({ title: res.data.msg || '登录失败', icon: 'none' })
      }
    } catch (error: any) {
      console.error('登录错误:', error)
      Taro.showToast({ title: error.message || '网络错误，请重试', icon: 'none' })
    } finally {
      setLoading(false)
    }
  }

  return (
    <View className="login-page min-h-screen bg-red-600 p-4 flex flex-col items-center justify-center">
      <View className="mb-10">
        <Text className="block text-7xl mb-4">🧧</Text>
        <Text className="block text-3xl font-bold text-white">春节幸运大转盘</Text>
        <Text className="block text-base text-red-100 mt-3">小店客户管理系统</Text>
      </View>

      <View className="w-full max-w-sm bg-white rounded-2xl p-8 shadow-lg">
        <View className="mb-5">
          <Text className="block text-lg font-semibold text-gray-800 mb-3">用户名</Text>
          <View className="bg-gray-50 rounded-xl px-5 py-4">
            <input
              className="w-full bg-transparent text-lg outline-none"
              placeholder="请输入用户名"
              value={username}
              onInput={(e) => setUsername(e.currentTarget.value)}
              disabled={loading}
            />
          </View>
        </View>

        <View className="mb-6">
          <Text className="block text-lg font-semibold text-gray-800 mb-3">密码</Text>
          <View className="bg-gray-50 rounded-xl px-5 py-4">
            <input
              className="w-full bg-transparent text-lg outline-none"
              type="password"
              placeholder="请输入密码"
              value={password}
              onInput={(e) => setPassword(e.currentTarget.value)}
              disabled={loading}
            />
          </View>
        </View>

        <button
          className={`w-full rounded-xl py-4 text-lg font-semibold ${
            loading ? 'bg-gray-400 text-gray-200' : 'bg-red-600 text-white active:bg-red-700'
          }`}
          onClick={handleLogin}
          disabled={loading}
        >
          {loading ? '登录中...' : '登录'}
        </button>

        <View className="mt-6 flex justify-between items-center">
          <Text className="text-sm text-gray-400">默认账号: admin / 密码: 123456</Text>
          <Text
            className="text-sm text-red-600 font-semibold"
            onClick={() => Taro.navigateTo({ url: '/pages/register/index' })}
          >
            去注册
          </Text>
        </View>
      </View>

      <View className="mt-8">
        <Text className="text-sm text-red-200">春节快乐 · 万事如意</Text>
      </View>
    </View>
  )
}

// archives/v4-architecture/mini-app/src/pages/login/index.vue
<template>
  <view class="login-page">
    <view class="container">
      <view class="title">登录</view>
      <view class="form">
        <view class="form-item">
          <input class="input" v-model="username" placeholder="请输入用户名" type="text" />
        </view>
        <view class="form-item">
          <input class="input" v-model="password" placeholder="请输入密码" type="password" />
        </view>
        <button class="submit-btn" @click="handleLogin" :disabled="loading">{{ loading ? '登录中...' : '登录' }}</button>
        <view class="register-link" @click="goToRegister">还没有账号？去注册</view>
      </view>
    </view>
  </view>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { api } from '../../services/api';

const username = ref('123456');
const password = ref('123456');
const loading = ref(false);

const handleLogin = async () => {
  if (!username.value || !password.value) {
    uni.showToast({ title: '请输入用户名和密码', icon: 'none' });
    return;
  }

  if (username.value.length < 2) {
    uni.showToast({ title: '用户名长度至少为2个字符', icon: 'none' });
    return;
  }

  loading.value = true;
  try {
    console.log('登录请求参数:', { username: username.value, password: password.value });
    const res = await api.auth.login({ username: username.value, password: password.value });
    console.log('登录响应:', res);
    uni.setStorageSync('token', res.token);
    uni.setStorageSync('user', res.user);
    uni.showToast({ title: '登录成功', icon: 'success' });
    uni.switchTab({ url: '/pages/index/index' });
  } catch (error: any) {
    console.error('登录错误:', error);
    uni.showToast({ 
      title: error.message || '登录失败', 
      icon: 'none',
      duration: 2000
    });
  } finally {
    loading.value = false;
  }
};

const goToRegister = () => {
  uni.navigateTo({ url: '/pages/register/index' });
};
</script>

<style lang="scss" scoped>
.login-page {
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: #f5f5f5;
}

.container {
  width: 90%;
  max-width: 400px;
  padding: 40rpx;
  background-color: white;
  border-radius: 20rpx;
  box-shadow: 0 8rpx 32rpx rgba(0, 0, 0, 0.1);
}

.title {
  font-size: 36rpx;
  font-weight: bold;
  color: #333;
  text-align: center;
  margin-bottom: 40rpx;
}

.form-item {
  margin-bottom: 30rpx;
}

.input {
  width: 100%;
  height: 88rpx;
  padding: 0 24rpx;
  border: 2rpx solid #ddd;
  border-radius: 12rpx;
  font-size: 28rpx;
  color: #333;
  background-color: #f9f9f9;
}

.input:focus {
  border-color: #dc2626;
  background-color: white;
  outline: none;
  box-shadow: 0 0 0 4rpx rgba(220, 38, 38, 0.1);
}

.submit-btn {
  width: 100%;
  height: 88rpx;
  background: linear-gradient(135deg, #dc2626 0%, #b91c1c 100%);
  color: white;
  border: none;
  border-radius: 12rpx;
  font-size: 32rpx;
  font-weight: bold;
  margin-top: 40rpx;
  display: flex;
  align-items: center;
  justify-content: center;
}

.submit-btn::after {
  border: none;
}

.submit-btn:active {
  opacity: 0.8;
  transform: scale(0.98);
}

.register-link {
  text-align: center;
  color: #dc2626;
  font-size: 24rpx;
  margin-top: 24rpx;
  cursor: pointer;
  padding: 16rpx;
}

.register-link:active {
  color: #b91c1c;
}
</style>
