// archives/v4-architecture/admin-web/src/pages/Product/index.vue
<template>
  <div class="product">
    <el-card>
      <template #header>
        <div class="card-header">
          <span>产品管理</span>
          <el-button type="primary" @click="handleAdd">新增产品</el-button>
        </div>
      </template>
      <el-table :data="tableData" style="width: 100%" v-loading="loading">
        <el-table-column prop="name" label="产品名称" />
        <el-table-column prop="category" label="分类" />
        <el-table-column prop="price" label="价格" />
        <el-table-column prop="stock" label="库存" />
        <el-table-column label="操作" width="200">
          <template #default="scope">
            <el-button size="small" @click="handleEdit(scope.row)">编辑</el-button>
            <el-button size="small" type="danger" @click="handleDelete(scope.row)">删除</el-button>
          </template>
        </el-table-column>
      </el-table>
    </el-card>

    <!-- 产品表单对话框 -->
    <el-dialog
      v-model="dialogVisible"
      :title="dialogTitle"
      width="500px"
    >
      <el-form :model="form" :rules="rules" ref="formRef" label-width="80px">
        <el-form-item label="产品名称" prop="name">
          <el-input v-model="form.name" placeholder="请输入产品名称" />
        </el-form-item>
        <el-form-item label="分类" prop="category">
          <el-input v-model="form.category" placeholder="请输入分类" />
        </el-form-item>
        <el-form-item label="价格" prop="price">
          <el-input-number v-model="form.price" :min="0" :step="0.01" placeholder="请输入价格" />
        </el-form-item>
        <el-form-item label="库存" prop="stock">
          <el-input-number v-model="form.stock" :min="0" placeholder="请输入库存" />
        </el-form-item>
        <el-form-item label="描述" prop="description">
          <el-input v-model="form.description" type="textarea" placeholder="请输入描述" />
        </el-form-item>
      </el-form>
      <template #footer>
        <span class="dialog-footer">
          <el-button @click="dialogVisible = false">取消</el-button>
          <el-button type="primary" @click="handleSubmit" :loading="submitLoading">确定</el-button>
        </span>
      </template>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, onMounted } from 'vue';
import { ElMessage, ElMessageBox, ElForm } from 'element-plus';
import type { FormInstance, FormRules } from 'element-plus';
import request from '@/api';

const loading = ref(false);
const submitLoading = ref(false);
const dialogVisible = ref(false);
const dialogTitle = ref('新增产品');
const formRef = ref<FormInstance>();
const tableData = ref<any[]>([]);

const form = reactive({
  id: null as number | null,
  name: '',
  category: '',
  price: 0,
  stock: 0,
  description: '',
});

const rules = reactive<FormRules>({
  name: [{ required: true, message: '请输入产品名称', trigger: 'blur' }],
  category: [{ required: true, message: '请输入分类', trigger: 'blur' }],
  price: [{ required: true, message: '请输入价格', trigger: 'blur' }],
  stock: [{ required: true, message: '请输入库存', trigger: 'blur' }],
});

// 获取产品列表
const getProducts = async () => {
  loading.value = true;
  try {
    const response = await request.get('/products');
    tableData.value = response || [];
  } catch (error) {
    console.error('获取产品列表失败:', error);
  } finally {
    loading.value = false;
  }
};

// 新增产品
const handleAdd = () => {
  dialogTitle.value = '新增产品';
  Object.assign(form, {
    id: '',
    name: '',
    category: '',
    price: 0,
    stock: 0,
    description: '',
  });
  dialogVisible.value = true;
};

// 编辑产品
const handleEdit = (row: any) => {
  dialogTitle.value = '编辑产品';
  Object.assign(form, row);
  dialogVisible.value = true;
};

// 删除产品
const handleDelete = (row: any) => {
  ElMessageBox.confirm('确定要删除该产品吗?', '提示', {
    confirmButtonText: '确定',
    cancelButtonText: '取消',
    type: 'warning',
  }).then(async () => {
    try {
      await request.delete(`/products/${row.id}`);
      ElMessage.success('删除成功');
      getProducts();
    } catch (error) {
      console.error('删除产品失败:', error);
    }
  });
};

// 提交表单
const handleSubmit = async () => {
  if (!formRef.value) return;
  await formRef.value.validate(async (valid) => {
    if (valid) {
      submitLoading.value = true;
      try {
        if (form.id) {
          await request.put(`/products/${form.id}`, form);
          ElMessage.success('更新成功');
        } else {
          await request.post('/products', form);
          ElMessage.success('新增成功');
        }
        dialogVisible.value = false;
        getProducts();
      } catch (error) {
        console.error('提交表单失败:', error);
      } finally {
        submitLoading.value = false;
      }
    }
  });
};

// 初始化
onMounted(() => {
  getProducts();
});
</script>

<style lang="scss" scoped>
.product {
  .card-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
  }

  .dialog-footer {
    width: 100%;
    display: flex;
    justify-content: flex-end;
  }
}
</style>

// src/pages/product/index.tsx
import { View, Text, Input, Button } from '@tarojs/components'
import { useState, useEffect } from 'react'
import Taro from '@tarojs/taro'
import { Network } from '@/network'

export default function ProductPage() {
  const [products, setProducts] = useState<any[]>([])
  const [loading, setLoading] = useState(false)
  const [showForm, setShowForm] = useState(false)
  const [editingProduct, setEditingProduct] = useState<any>(null)
  const [formData, setFormData] = useState({
    name: '',
    description: '',
    price: '',
    isActive: true
  })

  const fetchProducts = async () => {
    setLoading(true)
    try {
      const res = await Network.request({
        url: '/api/product',
        method: 'GET'
      })
      if (res.data.code === 200) {
        setProducts(res.data.data || [])
      }
    } catch (error) {
      console.error('获取产品列表失败:', error)
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    fetchProducts()
  }, [])

  const handleAdd = () => {
    setEditingProduct(null)
    setFormData({
      name: '',
      description: '',
      price: '',
      isActive: true
    })
    setShowForm(true)
  }

  const handleEdit = (product: any) => {
    setEditingProduct(product)
    setFormData({
      name: product.name,
      description: product.description || '',
      price: product.price,
      isActive: product.isActive
    })
    setShowForm(true)
  }

  const handleToggleStatus = async (id: string, isActive: boolean) => {
    try {
      await Network.request({
        url: `/api/product/${id}`,
        method: 'PUT',
        data: { isActive: !isActive }
      })
      Taro.showToast({ title: isActive ? '已下架' : '已上架', icon: 'success' })
      fetchProducts()
    } catch (error) {
      Taro.showToast({ title: '操作失败', icon: 'none' })
    }
  }

  const handleDelete = async (id: string) => {
    Taro.showModal({
      title: '确认删除',
      content: '确定要删除该产品吗？',
      success: async (res) => {
        if (res.confirm) {
          try {
            await Network.request({
              url: `/api/product/${id}`,
              method: 'DELETE'
            })
            Taro.showToast({ title: '删除成功', icon: 'success' })
            fetchProducts()
          } catch (error) {
            Taro.showToast({ title: '删除失败', icon: 'none' })
          }
        }
      }
    })
  }

  const handleSubmit = async () => {
    if (!formData.name) {
      Taro.showToast({ title: '请输入产品名称', icon: 'none' })
      return
    }
    if (!formData.price) {
      Taro.showToast({ title: '请输入产品价格', icon: 'none' })
      return
    }

    try {
      if (editingProduct) {
        await Network.request({
          url: `/api/product/${editingProduct.id}`,
          method: 'PUT',
          data: formData
        })
        Taro.showToast({ title: '更新成功', icon: 'success' })
      } else {
        await Network.request({
          url: '/api/product',
          method: 'POST',
          data: formData
        })
        Taro.showToast({ title: '添加成功', icon: 'success' })
      }
      setShowForm(false)
      fetchProducts()
    } catch (error) {
      Taro.showToast({ title: '操作失败', icon: 'none' })
    }
  }

  if (showForm) {
    return (
      <View className="product-page min-h-screen bg-gray-50 p-4">
        <View className="flex items-center mb-4">
          <Button onClick={() => setShowForm(false)} size="mini">返回</Button>
          <Text className="ml-4 text-xl font-bold text-gray-800">
            {editingProduct ? '编辑产品' : '新增产品'}
          </Text>
        </View>

        <View className="bg-white rounded-2xl p-4 shadow-sm">
          <View className="mb-4">
            <Text className="block text-sm font-semibold text-gray-800 mb-2">产品名称 *</Text>
            <View className="bg-gray-50 rounded-xl px-4 py-3">
              <Input
                className="w-full bg-transparent"
                placeholder="请输入产品名称"
                value={formData.name}
                onInput={(e) => setFormData({ ...formData, name: e.detail.value })}
              />
            </View>
          </View>

          <View className="mb-4">
            <Text className="block text-sm font-semibold text-gray-800 mb-2">产品描述</Text>
            <View className="bg-gray-50 rounded-xl px-4 py-3">
              <Input
                className="w-full bg-transparent"
                placeholder="请输入产品描述"
                value={formData.description}
                onInput={(e) => setFormData({ ...formData, description: e.detail.value })}
              />
            </View>
          </View>

          <View className="mb-4">
            <Text className="block text-sm font-semibold text-gray-800 mb-2">产品价格 *</Text>
            <View className="bg-gray-50 rounded-xl px-4 py-3">
              <Input
                className="w-full bg-transparent"
                type="digit"
                placeholder="请输入产品价格"
                value={formData.price}
                onInput={(e) => setFormData({ ...formData, price: e.detail.value })}
              />
            </View>
          </View>

          <View className="mb-4">
            <Text className="block text-sm font-semibold text-gray-800 mb-2">状态</Text>
            <View
              className={`rounded-xl px-4 py-3 ${formData.isActive ? 'bg-green-50 text-green-600' : 'bg-gray-100 text-gray-600'}`}
              onClick={() => setFormData({ ...formData, isActive: !formData.isActive })}
            >
              <Text className="block">{formData.isActive ? '✓ 已上架' : '✗ 已下架'}</Text>
            </View>
          </View>

          <Button
            className="w-full bg-red-600 text-white rounded-xl py-3 font-semibold"
            onClick={handleSubmit}
          >
            保存
          </Button>
        </View>
      </View>
    )
  }

  return (
    <View className="product-page min-h-screen bg-gray-50 p-4">
      <View className="flex justify-between items-center mb-4">
        <Text className="text-xl font-bold text-gray-800">产品管理</Text>
        <Button
          className="bg-red-600 text-white rounded-lg px-4 py-2 text-sm"
          onClick={handleAdd}
        >
          新增产品
        </Button>
      </View>

      {loading ? (
        <View className="flex flex-col items-center justify-center py-16">
          <Text className="block text-sm text-gray-500">加载中...</Text>
        </View>
      ) : products.length === 0 ? (
        <View className="flex flex-col items-center justify-center py-16">
          <Text className="block text-6xl mb-4">📦</Text>
          <Text className="block text-lg font-semibold text-gray-600 mb-2">暂无产品</Text>
          <Text className="block text-sm text-gray-400">点击上方按钮添加产品</Text>
        </View>
      ) : (
        <View className="space-y-3">
          {products.map((product) => (
            <View key={product.id} className="bg-white rounded-xl p-4 shadow-sm">
              <View className="flex justify-between items-start">
                <View className="flex-1">
                  <Text className="block text-base font-semibold text-gray-800 mb-1">
                    {product.name}
                  </Text>
                  {product.description && (
                    <Text className="block text-sm text-gray-500 mb-1">
                      {product.description}
                    </Text>
                  )}
                  <Text className="block text-lg text-orange-500 font-semibold mb-1">
                    ¥{product.price}
                  </Text>
                  <Text className={`text-xs ${product.isActive ? 'text-green-500' : 'text-gray-400'}`}>
                    {product.isActive ? '已上架' : '已下架'}
                  </Text>
                </View>
                <View className="flex flex-col gap-2 ml-4">
                  <Button
                    size="mini"
                    type={product.isActive ? 'warn' : 'primary'}
                    onClick={() => handleToggleStatus(product.id, product.isActive)}
                  >
                    {product.isActive ? '下架' : '上架'}
                  </Button>
                  <Button size="mini" onClick={() => handleEdit(product)}>编辑</Button>
                  <Button size="mini" onClick={() => handleDelete(product.id)}>删除</Button>
                </View>
              </View>
            </View>
          ))}
        </View>
      )}
    </View>
  )
}
