// archives/v1.0/src/pages/register/index.tsx
import { View, Text, Input, Button } from '@tarojs/components'
import { useState } from 'react'
import Taro from '@tarojs/taro'
import { Network } from '@/network'

export default function RegisterPage() {
  const [formData, setFormData] = useState({
    username: '',
    password: '',
    confirmPassword: '',
    name: '',
    phone: ''
  })
  const [loading, setLoading] = useState(false)

  const handleInputChange = (field: string, value: string) => {
    setFormData(prev => ({ ...prev, [field]: value }))
  }

  const validateForm = () => {
    if (!formData.username) {
      Taro.showToast({ title: '请输入用户名', icon: 'none' })
      return false
    }
    if (formData.username.length < 3) {
      Taro.showToast({ title: '用户名至少3个字符', icon: 'none' })
      return false
    }
    if (!formData.password) {
      Taro.showToast({ title: '请输入密码', icon: 'none' })
      return false
    }
    if (formData.password.length < 6) {
      Taro.showToast({ title: '密码至少6个字符', icon: 'none' })
      return false
    }
    if (formData.password !== formData.confirmPassword) {
      Taro.showToast({ title: '两次密码不一致', icon: 'none' })
      return false
    }
    if (!formData.name) {
      Taro.showToast({ title: '请输入姓名', icon: 'none' })
      return false
    }
    return true
  }

  const handleRegister = async () => {
    if (!validateForm()) return

    setLoading(true)
    try {
      console.log('开始注册请求...', formData)

      const res = await Network.request({
        url: '/api/auth/register',
        method: 'POST',
        data: {
          username: formData.username,
          password: formData.password,
          name: formData.name,
          role: 'customer', // 默认注册为客户角色
          phone: formData.phone
        }
      })

      console.log('注册响应:', res)

      if (res.data.code === 200) {
        Taro.showToast({ title: '注册成功', icon: 'success' })

        // 注册成功后自动登录
        setTimeout(() => {
          // 保存登录信息
          Taro.setStorageSync('token', res.data.data.token)
          Taro.setStorageSync('userInfo', res.data.data.user)

          Taro.showToast({ title: '登录成功', icon: 'success' })

          // 跳转到抽奖页面
          setTimeout(() => {
            Taro.reLaunch({ url: '/pages/index/index' })
          }, 1000)
        }, 1000)
      } else {
        Taro.showToast({ title: res.data.msg || '注册失败', icon: 'none' })
      }
    } catch (error: any) {
      console.error('注册错误:', error)
      Taro.showToast({ title: error.message || '网络错误，请重试', icon: 'none' })
    } finally {
      setLoading(false)
    }
  }

  const handleBackToLogin = () => {
    Taro.navigateBack()
  }

  return (
    <View className="register-page min-h-screen bg-red-600 p-4 flex flex-col items-center justify-center">
      <View className="mb-10">
        <Text className="block text-7xl mb-4">🧧</Text>
        <Text className="block text-3xl font-bold text-white">用户注册</Text>
        <Text className="block text-base text-red-100 mt-3">注册成为客户，参与抽奖赢大奖</Text>
      </View>

      <View className="w-full max-w-sm bg-white rounded-2xl p-8 shadow-lg">
        <View className="mb-5">
          <Text className="block text-lg font-semibold text-gray-800 mb-3">用户名 *</Text>
          <View className="bg-gray-50 rounded-xl px-5 py-4">
            <Input
              className="w-full bg-transparent text-lg outline-none"
              placeholder="请输入用户名（至少3个字符）"
              value={formData.username}
              onInput={(e) => handleInputChange('username', e.detail.value)}
              disabled={loading}
            />
          </View>
        </View>

        <View className="mb-5">
          <Text className="block text-lg font-semibold text-gray-800 mb-3">姓名 *</Text>
          <View className="bg-gray-50 rounded-xl px-5 py-4">
            <Input
              className="w-full bg-transparent text-lg outline-none"
              placeholder="请输入真实姓名"
              value={formData.name}
              onInput={(e) => handleInputChange('name', e.detail.value)}
              disabled={loading}
            />
          </View>
        </View>

        <View className="mb-5">
          <Text className="block text-lg font-semibold text-gray-800 mb-3">手机号</Text>
          <View className="bg-gray-50 rounded-xl px-5 py-4">
            <Input
              className="w-full bg-transparent text-lg outline-none"
              type="number"
              placeholder="请输入手机号（选填）"
              value={formData.phone}
              onInput={(e) => handleInputChange('phone', e.detail.value)}
              disabled={loading}
            />
          </View>
        </View>

        <View className="mb-5">
          <Text className="block text-lg font-semibold text-gray-800 mb-3">密码 *</Text>
          <View className="bg-gray-50 rounded-xl px-5 py-4">
            <Input
              className="w-full bg-transparent text-lg outline-none"
              password
              placeholder="请输入密码（至少6个字符）"
              value={formData.password}
              onInput={(e) => handleInputChange('password', e.detail.value)}
              disabled={loading}
            />
          </View>
        </View>

        <View className="mb-6">
          <Text className="block text-lg font-semibold text-gray-800 mb-3">确认密码 *</Text>
          <View className="bg-gray-50 rounded-xl px-5 py-4">
            <Input
              className="w-full bg-transparent text-lg outline-none"
              password
              placeholder="请再次输入密码"
              value={formData.confirmPassword}
              onInput={(e) => handleInputChange('confirmPassword', e.detail.value)}
              disabled={loading}
            />
          </View>
        </View>

        <Button
          className={`w-full rounded-xl py-4 text-lg font-semibold ${
            loading ? 'bg-gray-400 text-gray-200' : 'bg-red-600 text-white active:bg-red-700'
          }`}
          onClick={handleRegister}
          disabled={loading}
        >
          {loading ? '注册中...' : '注册'}
        </Button>

        <View className="mt-6 flex justify-between items-center">
          <Text className="text-sm text-gray-400">注册即表示同意用户协议</Text>
          <Text
            className="text-sm text-red-600"
            onClick={handleBackToLogin}
          >
            已有账号？去登录
          </Text>
        </View>
      </View>

      <View className="mt-8">
        <Text className="text-sm text-red-200">春节快乐 · 万事如意</Text>
      </View>
    </View>
  )
}

// mini-app/src/pages/register/index.vue
<template>
  <view class="register-page">
    <view class="container">
      <view class="title">注册</view>
      <view class="form">
        <view class="form-item">
          <input class="input" v-model="name" placeholder="请输入姓名" />
        </view>
        <view class="form-item">
          <input class="input" v-model="username" placeholder="请输入用户名" type="text" />
        </view>
        <view class="form-item">
          <input class="input" v-model="password" placeholder="请输入密码" type="password" />
        </view>
        <view class="form-item">
          <input class="input" v-model="confirmPassword" placeholder="请确认密码" type="password" />
        </view>
        <button class="submit-btn" @click="handleRegister" :disabled="loading">{{ loading ? '注册中...' : '注册' }}</button>
        <view class="login-link" @click="goToLogin">已有账号？去登录</view>
      </view>
    </view>
  </view>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { api } from '../../services/api';

const name = ref('');
const username = ref('');
const password = ref('');
const confirmPassword = ref('');
const loading = ref(false);

const handleRegister = async () => {
  if (!name.value || !username.value || !password.value || !confirmPassword.value) {
    uni.showToast({ title: '请填写完整信息', icon: 'none' });
    return;
  }

  if (password.value !== confirmPassword.value) {
    uni.showToast({ title: '两次密码不一致', icon: 'none' });
    return;
  }

  if (username.value.length < 2) {
    uni.showToast({ title: '用户名长度至少为2个字符', icon: 'none' });
    return;
  }

  loading.value = true;
  try {
    await api.auth.register({ 
      name: name.value, 
      username: username.value, 
      password: password.value 
    });
    uni.showToast({ title: '注册成功，请登录', icon: 'success' });
    uni.navigateBack();
  } catch (error: any) {
    uni.showToast({ title: error.message || '注册失败', icon: 'none' });
  } finally {
    loading.value = false;
  }
};

const goToLogin = () => {
  uni.navigateBack();
};
</script>

<style lang="scss" scoped>
.register-page {
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: #f5f5f5;
}

.container {
  width: 90%;
  padding: 40rpx;
  background-color: #ffffff;
  border-radius: 20rpx;
}

.title {
  font-size: 48rpx;
  font-weight: bold;
  color: #333333;
  text-align: center;
  margin-bottom: 60rpx;
}

.form-item {
  margin-bottom: 30rpx;
}

.input {
  width: 100%;
  height: 88rpx;
  padding: 0 30rpx;
  border: 2rpx solid #e5e7eb;
  border-radius: 10rpx;
  font-size: 28rpx;
}

.submit-btn {
  width: 100%;
  height: 88rpx;
  background-color: #dc2626;
  color: #ffffff;
  border: none;
  border-radius: 10rpx;
  font-size: 32rpx;
  font-weight: bold;
  margin-top: 40rpx;
}

.login-link {
  text-align: center;
  color: #dc2626;
  font-size: 28rpx;
  margin-top: 30rpx;
}
</style>
